# action.yml
name: 'Swagger Codegen CLI'
description: 'Run Swagger Codegen with Github Actions'
branding:
    icon: code
    color: green
runs:
  using: 'docker'
  image: 'docker://swaggerapi/swagger-codegen-cli:2.4.32'
  args:
  - ${{ inputs.action }}
  - '-i'
  - ${{ inputs.input }}
  - '-l'
  - 'python'
  - '-o'
  - ${{ inputs.output }}
  - '-DpackageName=cudo_compute'
inputs:
  input:
    description: Swagger file
    required: true
  action:
    description: swagger-codegen-cli action
    required: true
  output:
    description: output directory
    required: true



